---
title: "My Fantasy Team"
author: "Jordan Wozniak"
date: "9/11/2025"
categories: [welcome, fantasyteam]
image: ""
format: html
---


# My Fantasy Team Introduction! {#sec-myFantasyTeamIntro}

I have had the opportunity to participate in my class' fantasy football draft, where we drafted a whole team with 5 people, 1 extra bot player, with a QB, 2 RB, 2 WR, 1 TE, 1 FLEX, 1 DEF, 1 K, and 6 BENCH spots. How I organize who I drafted will be the the order in which: I drafted them, my justification, their strengths and weaknesses.

# Who Did I Draft? {#sec-whoDraft}

-First Pick - Saquon Barkley (RB) The name of the game is the running back, and that would fall onto Saquon as one of the best at it. This is observed through his last season with the Eagles, where he nearly broke the rushing record, and his last several season with the Giants, where they looked decent, and then horrible without him. His strength here is that teams haven't figured out how to stop him. His weakness is that the Eagles offense also have Jalen Hurts who is a mobile QB, and could take away touches from Saquon.

-Second Pick - Justin Jefferson (WR): Justin Jefferson is a prolific scorer and receiving machine. He has been one of the top receiving yards leader for many season, and will continue to do so. His strength would be that the Vikings don't have any relative WRs that can compete to take away Justin Jefferson's targets. His weakness his solely on the fact that he is the only receiver, and will be prone to be double-teamed and the Vikings are also trying out a new QB in J.J. McCarthy.

-Third Pick - Amon-Ra St. Brown (WR): Amon-Ra, just like Justin Jefferson, has the same profile as him, where he has been leading the Lions in receiving yards for years and will continue to grow. His strength here is that the Lions are evenly mixed with the run game and throwing through the air, and with the veteran QB, Jared Goff. His weakness would be on that since the Lions are well versed in talent, it may take away his targets.

-Fourth Pick - Ashton Jeanty (RB): I would've considered this as a hailmary in picking a top RB. Since I only have the evidence of how well he did was from leading Boise State to being a relevant team. His strength would be that he is a young RB, a lot of energy. This would lead into his weakness, where there is a lot of uncertainty to it.

-Fifth Pick - George Kittle (TE): This would be a personal pick since he went to the University of Iowa, put he is one of the best TEs in the league at this current moment. What would in-turn be his strength. His weakness would be that TEs don't see as many targets as WRs, since WRs are faster and TEs mix in their blocking ability, so it could limit him in points

-Sixth Pick - Alvin Kamara (RB): I was initially surprised that he wasn't picked earlier in our draft, he has analyzed through many years that he is the offense. His strength is that he is a dual threat. There would be many weeks where he would double the amount of receiving yards versus his amount of rushing yards. In a PPR (Points Per Reception) league, this can elevate him high. His weakness is that there is a shaky QB room, and could affect the output for Kamara.

-Seventh Pick - Denver Broncos (DEF): Usually from my analytical eyes, defenses are usually slept on and kept for the end of the draft, and I wanted to break that cycle. The strength for the Broncos defense is that they have a top 5 player, and a few top defensive players and the Broncos as a whole have been defensive heavy. The weakness is that defenses are unpredictable with why they would allow points and yards, and there are more people (11 versus 1), and injuries can hurt.

-Eighth Pick - Chase Brown (RB): This player is fairly young, and had a break out year after the depature of Joe Mixon. His strength is that, as said, is young. Weakness is that the Bengals' offense is shaky.

-Ninth Pick - Tyreek Hill (WR): Still a top, fast WR. His strength would be that Tyreek, no matter the defense, can expose them. His weakness is that he has a poor morale with the team, and can affect him.

-Tenth Pick - Baker Mayfield (QB): I finally picked a QB, but waited patiently for one. I am satisfied with this pick since the Bucs are offense heavy. That would turn into his strength, that he is a good QB. His weakness is that, through previous seasons, is that he can have those high ups and downs.

-Eleventh Pick - Brock Purdy (QB): Brock Purdy has proved to be a good pick as QB1 for some fantasy teams. The 49ers offense has a lot of weapons. However, sometimes Purdy gets overwhelmed and performs low.

-Twelfth Pick - Travis Kelce (TE): Kelce is a consistent high pick in some leagues, and has been consistent when it comes to being a top receiver for Mahomes. 

-Thirteenth Pick - Terry McLaurin (WR): As the name implies, he is scary, which makes him a good backup receiver. A weakness that he has is that he can widely vary in points, and has been observed for years.

-Fourteenth Pick - Cam Little (K): Simple to pick this kicker. He has been consistent, watch him kick a record breaking FG. As with many kickers, they can either show up or not show up, this would be the weakness for him, and can be said for many kickers.

-Fifteenth Pick - Cooper Kupp (WR): This is an honor pick for my team. Kupp, while on the Rams, has been one of the top receivers in the league, and will continue to do so on his new team, the Seahawks. However, he is paired with another top receiver in Smith-Njigba, and Kenneth Walker III.


# Team Plan {#sec-teamPlan}

My way to address all of these weaknesses is to run with what I have since I have a lot of up-side compared to the down-side. Looking at my team as a whole and wanted to pick out one overall weakness, it would be that I waited to pick a QB until my own tenth pick, missed out of other great talent, but still confident.

# My Prediction {#sec-prediction}

Analyzing my team at a deeper level, I believe that I have enough talent to carry myself to the top of the rankings. I would say around a 10-4 to a 12-2 record, I have a high ceiling. To win the whole league, I would give it an 80%.